#!/usr/bin/env python3
"""
Writes testdata/scoring_vectors.json: inputs and expected outputs of every Grit / Flow / score
formula plus the jump detection constants, computed with the analyser (tools/mtbdyn/scoring.py).

Both test suites read the file: tools/tests/test_parity.py checks the Python formulas against
it and ScoringParityTest.kt checks Scoring.kt / MtbConfig.kt. Change a formula on one side,
re-run this script, and the other side's test fails until it matches.

  python3 tools/make_scoring_vectors.py
"""
from __future__ import annotations

import itertools
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from mtbdyn import imu, scoring  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "testdata", "scoring_vectors.json")

GRADES = [-30.0, -18.0, -12.0, -6.0, -2.5, 0.0, 4.0, 8.0, 16.0, 40.0, None]
CURVATURES = [0.0, 0.02, 1 / 15, 0.2, 0.5, None]
ROUGH = [None, 0.2, 0.6, 1.2, 2.5]


def build() -> dict:
    cases: list[dict] = []

    def add(fn: str, args: list, value: float) -> None:
        cases.append({"fn": fn, "args": args, "expected": value})

    for g, k, r in itertools.product(GRADES, CURVATURES, ROUGH):
        add("gritPerSecond", [g, k, r], scoring.grit_per_second(g, k, r))
    for obs, v, g in itertools.product([-3.0, -1.0, 0.0, 0.5], [0.0, 3.0, 8.0, 15.0], GRADES):
        add("brakingDecel", [obs, v, g], scoring.braking_decel(obs, v, g))
    for d in [0.0, 0.2, 0.3, 0.6, 0.9, 1.5, 2.5]:
        add("brakeWeight", [d], scoring.brake_weight(d))
    for v, k, g, r in itertools.product([2.0, 6.0, 12.0], CURVATURES, [-20.0, -10.0, -3.0, 0.0, None], ROUGH):
        add("brakingNecessity", [v, k, g, r], scoring.braking_necessity(v, k, g, r))
    for f, d in [(0.0, 0.0), (5.0, 0.5), (12.0, 1000.0), (80.0, 2500.0)]:
        add("flowScore", [f, d], scoring.flow_score(f, d))
    for x in [0.0, 1.25, 2.0, 4.4, 10.5, 30.0]:
        add("difficultyScore", [x], scoring.difficulty_score(x))
    for x in [0.0, 0.4, 3.1, 6.0, 20.0]:
        add("smoothnessScore", [x], scoring.smoothness_score(x))
    for x in [0.0, 0.5, 2.8, 6.0, 40.0]:
        add("airScore", [x], scoring.air_score(x))
    for d, s, a in [(0.0, 0.0, 0.0), (61.0, 94.0, 37.0), (100.0, 100.0, 100.0)]:
        add("mtbScore", [d, s, a], scoring.mtb_score(d, s, a))
    for air, drop in itertools.product([0.0, 0.28, 0.5, 0.83, 1.4], [None, -0.5, 0.0, 1.0, 3.0]):
        add("jumpHeight", [air, drop], scoring.jump_height(air, drop))

    return {
        "comment": "Generated by tools/make_scoring_vectors.py from tools/mtbdyn; read by tools/tests/test_parity.py "
                   "and app/src/test/.../ScoringParityTest.kt. null = missing value (NaN on the Karoo).",
        "constants": {
            "G": scoring.G, "MOVING_SPEED": scoring.MOVING_SPEED, "GRIT_SCALE": scoring.GRIT_SCALE,
            "GRIT_W_GRADE": scoring.GRIT_W_GRADE, "GRIT_W_TURN": scoring.GRIT_W_TURN, "GRIT_W_ROUGH": scoring.GRIT_W_ROUGH,
            "CRR": scoring.CRR, "AIR_K": scoring.AIR_K, "BRAKE_MIN": scoring.BRAKE_MIN, "BRAKE_FULL": scoring.BRAKE_FULL,
            "BRAKING_THRESHOLD": scoring.BRAKING_THRESHOLD, "DESCENT_GRADE": scoring.DESCENT_GRADE,
            "MAX_LATERAL_G": scoring.MAX_LATERAL_G, "FLOW_LAG": scoring.DEFAULT_FLOW_LAG,
            "JUMP_LAND_G": imu.LAND_G, "JUMP_MAX_AIR": imu.MAX_AIR, "JUMP_MAX_MEAN_AIR_G": imu.MAX_MEAN_AIR_G,
            "JUMP_GLITCH": imu.GLITCH, "JUMP_LANDING_WINDOW": imu.LANDING_WINDOW, "JUMP_COOLDOWN": imu.COOLDOWN,
            "JUMP_MIN_SPEED": imu.MIN_JUMP_SPEED,
        },
        "presets": {name: {"takeoffG": t, "minAirSec": a, "minLandingG": land} for name, (t, a, land) in imu.PRESETS.items()},
        "cases": cases,
    }


if __name__ == "__main__":
    data = build()
    cases = data.pop("cases")
    text = json.dumps(data, indent=1)[:-2]  # one case per line keeps diffs readable
    text += ',\n "cases": [\n' + ",\n".join("  " + json.dumps(c) for c in cases) + "\n ]\n}\n"
    with open(OUT, "w") as f:
        f.write(text)
    print(f"{len(cases)} cases -> {os.path.normpath(OUT)}")
